### ISSUE TITLE
在本机启动该程序是不是就不用想办法获取cf_clearance了?

### ISSUE THREAD

**Issue by 159957893905** [gtoxlili/wechat-chatGPT#11]
我的思路是这样的: 本机启动程序, 然后session-token, cf_clearance, user-agent3个值都直接通过浏览器复制过来, 再通过内网穿透工具提供给微信开放平台调用, 实际也都配置成功了, 但是调用的时候还是不行, 报错见下图:
![image](https://user-images.githubusercontent.com/29136201/207498066-82f08119-795f-44f1-9826-141b40095ae6.png)
好像还是 cf_clearance这里出错了, 然后程序就退出了
是这种方式不行么, 还是那里配置错了? 求解答

**Comment by gtoxlili** [comment]
程序会退出的问题已经修复了，请拉取最新的代码，然后本机启动程序, 然后session-token, cf_clearance, user-agent3个值都直接通过浏览器复制过来的逻辑是没问题的，你可以将 配置文件中 debug选项打开然后访问 127.0.0.1:7458/healthCheck 试下是否会出问题

**Comment by zed-gitub** [comment]
更新到了最新代码, 访问healthCheck还是跟之前一样的情况
![image](https://user-images.githubusercontent.com/29136201/207525606-2c06fe7b-4f8d-4b7c-983e-deb19dda580a.png)

**Comment by gtoxlili** [comment]
还是  cf_clearance 的问题，可能是因为你在浏览器获得的cf_clearance 是走了代理的，而程序本身的环境是不走代理的？

**Comment by zed-gitub** [comment]
还真是, 我把VPN关掉了就好了, 多谢~
