### ISSUE TITLE
求出视频版教程（小白看不太懂）

### ISSUE THREAD

**Issue by zjrwtx** [gtoxlili/wechat-chatGPT#13]

**Comment by shenjia** [comment]
话说这本来就不是给小白用的[捂脸]

再说了，因为微信平台的限制，目前架设好了之后也基本用不了，就给像我这样的受虐狂折腾享受下过程就好了……

**Comment by zjrwtx** [comment]
> 话说这本来就不是给小白用的[捂脸]
> 
> 再说了，因为微信平台的限制，目前架设好了之后也基本用不了，就给像我这样的受虐狂折腾享受下过程就好了……

那好吧，就是说，现在架设好也用不了吗
