### ISSUE TITLE
Mac 系统遇到一些初始化错误

### ISSUE THREAD

**Issue by liyandada** [gtoxlili/wechat-chatGPT#2]
当我在 sessionToken  中增加  __Secure-next-auth.session-token 后，运行出现错误
错误代码如下： 

$ go run main.go
2022/12/09 16:45:16 net/http: invalid byte '\n' in Cookie.Value; dropping invalid bytes
INFO[2022-12-09 16:45:16] Server listening at [::]:7458
panic: interface conversion: interface {} is nil, not string

goroutine 6 [running]:
wx-ChatGPT/chatGPT.(*ChatGPT).updateSessionToken(0xc000024520)
	/Users/li/chatGPT/wechat-chatGPT/chatGPT/chatGPT.go:83 +0x525
wx-ChatGPT/chatGPT.newChatGPT.func1()
	/Users/li/chatGPT/wechat-chatGPT/chatGPT/chatGPT.go:45 +0x25
created by wx-ChatGPT/chatGPT.newChatGPT
	/Users/li/chatGPT/wechat-chatGPT/chatGPT/chatGPT.go:44 +0xef
exit status 2

**Comment by gtoxlili** [comment]
应该是文件里多了空格，把token尾巴的空格删了就好

**Comment by liyandada** [comment]
后续遇到了这样的问题： 

kylin@kylin:~/wechat-chatGPT$ go run main.go  
go: finding github.com/go-chi/chi/v5 v5.0.7
go: finding github.com/go-chi/render v1.0.2
go: finding github.com/ajg/form v1.5.1
go: finding github.com/sirupsen/logrus v1.9.0
go: finding golang.org/x/sys v0.0.0-20220715151400-c0bba94af5f8
go: finding golang.org/x/sync v0.1.0
go: finding github.com/google/uuid v1.3.0
go: finding github.com/banzaicloud/logrus-runtime-formatter v0.0.0-20190729070250-5ae5475bae5e
# wx-ChatGPT/util
util/map.go:5:12: syntax error: unexpected comparable, expecting ]
util/map.go:9:13: syntax error: unexpected [, expecting comma or )
util/map.go:16:13: syntax error: unexpected [, expecting comma or )
util/map.go:20:13: syntax error: unexpected [, expecting comma or )
util/map.go:21:45: method has multiple receivers
util/map.go:21:46: syntax error: unexpected {, expecting (
util/map.go:22:3: syntax error: unexpected return, expecting )
util/map.go:26:13: syntax error: unexpected [, expecting comma or )
util/map.go:30:13: syntax error: unexpected [, expecting comma or )
util/map.go:32:29: method has multiple receivers
util/map.go:32:29: too many errors
note: module requires Go 1.19

**Comment by naturo267** [comment]
感觉有点厉害，最近openai真的好火

**Comment by naturo267** [comment]
有更新吗？
