### ISSUE TITLE
可以考虑使用客服消息回调

### ISSUE THREAD

**Issue by sunshanpeng** [gtoxlili/wechat-chatGPT#5]
我看目前使用的是接收消息同步调用chatgpt然后返回，可以考虑使用客服消息异步返回：[客服消息接口](https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Service_Center_messages.html#%E5%AE%A2%E6%9C%8D%E6%8E%A5%E5%8F%A3-%E5%8F%91%E6%B6%88%E6%81%AF)

**Comment by gtoxlili** [comment]
只有个人号(

**Comment by shenjia** [comment]
得注册服务号才行。坑
