### ISSUE TITLE
接收消息时报错

### ISSUE THREAD

**Issue by piaoxue1949** [gtoxlili/wechat-chatGPT#6]
![1670900791685](https://user-images.githubusercontent.com/10650603/207216584-468b2eab-9890-43a5-9d0d-91dab1e81574.png)
其中xml这一段是收到的消息体，byte数组打印是在SendMsg函数中convert.ToChatRes(endBlock)打印的endBlock参数

**Comment by gtoxlili** [comment]
看起来像是没过盾导致的从 chatGPT 那获取的 res 返回了别的了，本机的 cf_clearance 服务器是用不了的，得 通过 [vvanglro/cf-clearance](https://github.com/vvanglro/cf-clearance) 使用模拟方式过盾，然后把这里的 cf_clearance 填进配置文件里

**Comment by shenjia** [comment]
我这是不是也是cl_clearance的问题？

INFO[2022-12-13 20:31:39] [消息接收] Type: text, From: ogY6UuP9-yMo-VAyj4zlyBvYrOLY, MsgId: 23922035821866418, Content: 你好
FATA[2022-12-13 20:31:39] 初始化失败:  invalid character '\n' in string literal  file=/root/wechat-chatGPT/chatGPT/chatGPT.go function=func1 line=37 package=wxChatGPT/chatGPT.newChatGPT

**Comment by shenjia** [comment]
看上去需要XVFB之类的图形交互界面来获取，这在linode下貌似不好太好实现，吐血了

**Comment by shenjia** [comment]
> 看起来像是没过盾导致的从 chatGPT 那获取的 res 返回了别的了，本机的 cf_clearance 服务器是用不了的，得 通过 [vvanglro/cf-clearance](https://github.com/vvanglro/cf-clearance) 使用模拟方式过盾，然后把这里的 cf_clearance 填进配置文件里

我在linode上试了半天都拿不到cf_clearance。跑脚本结果是：

║ Looks like you launched a headed browser without having a XServer running.                     ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║                                                                                                ║
║ <3 Playwright Team                                                                             ║

看文档说要用xvfb，但用xvfb-run跑什么根本不知道。
cfscrape 也试了，一直HTTPError: 403 Client Error: Forbidden for url。

兄弟你是什么环境部署的？

**Comment by shenjia** [comment]
我看openai官网的文档，直接用curl都可以调用api，貌似根本不用cf_clearance啊？

**Comment by gtoxlili** [comment]
> 我看openai官网的文档，直接用curl都可以调用api，貌似根本不用cf_clearance啊？

openai的接口结果和chatgpt是不一样的，chatgpt会更加智能，目前项目用的是 chat.openai.com 逆向出来的接口

**Comment by shenjia** [comment]
原来如此。我怎么觉得playground出来的内容质量会更高一点啊……chatgpt的接口目前是不是免费可以长期用的？另外你是怎么解决上下文问题的，如何标记开始新的Thread？如果共用一个Thread的话，多用户同时交互时上下文应该会混乱的吧？

**Comment by gtoxlili** [comment]
> 原来如此。我怎么觉得playground出来的内容质量会更高一点啊……chatgpt的接口目前是不是免费可以长期用的？另外你是怎么解决上下文问题的，如何标记开始新的Thread？如果共用一个Thread的话，多用户同时交互时上下文应该会混乱的吧？

这个解释起来有点复杂，可以自行去代码里看看，这部分的代码实现自我感觉写的还是挺巧妙的 (

**Comment by shenjia** [comment]
> > 原来如此。我怎么觉得playground出来的内容质量会更高一点啊……chatgpt的接口目前是不是免费可以长期用的？另外你是怎么解决上下文问题的，如何标记开始新的Thread？如果共用一个Thread的话，多用户同时交互时上下文应该会混乱的吧？
> 
> 这个解释起来有点复杂，可以自行去代码里看看，这部分的代码实现自我感觉写的还是挺巧妙的 (

学习了，原来是做了一个map映射：）

能否指点下怎么用[vvanglro/cf-clearance](https://github.com/vvanglro/cf-clearance)过盾呀？莫非要部署一个带GUI的linode才行吗？

**Comment by shenjia** [comment]
> 

搞定了。用glish登录linode，然后xfvb-run启动python来运行脚本，输出内容导出后再复制到config.json里。

**Comment by gtoxlili** [comment]
> > 看起来像是没过盾导致的从 chatGPT 那获取的 res 返回了别的了，本机的 cf_clearance 服务器是用不了的，得 通过 [vvanglro/cf-clearance](https://github.com/vvanglro/cf-clearance) 使用模拟方式过盾，然后把这里的 cf_clearance 填进配置文件里
> 
> 我在自己电脑上面运行的wechat-chatGPT, 想通过内网穿透来使用, 然后session-token, cf_clearance, user-agent都填的是本机浏览器获取到的值, 为啥还是会出现这个issues出现的问题? cf_clearance不是只要IP和user-agent一样就能过么, 我都是本机访问的, 应该都一样的呀...

具体错误发一下，还有请不要在已经关闭的issue里提问
