### ISSUE TITLE
编译后运行项目，访问127.0.0.1:7458提示404 Page not found

### ISSUE THREAD

**Issue by shenjia** [gtoxlili/wechat-chatGPT#7]
如题，我已经在config.json中填好了session-token和cf_clearance，并用提供的命令（替换了微信Token）进行编译，但运行起来之后访问接口提示404 Page not found.

`curl 127.0.0.1:7458
404 page not found`

此时服务端的日志如下：

`
INFO[2022-12-13 18:57:14] Server listening at [::]:7458
INFO[2022-12-13 19:00:31] "GET http://127.0.0.1:7458/ HTTP/1.1" from 127.0.0.1:37668 - 404 19B in 18.37µs`

请问可能是哪里出了问题？

**Comment by gtoxlili** [comment]
因为并没有这个路由啊

**Comment by gtoxlili** [comment]
确实在 Readme里没写清楚 和微信公众平台对接的路由应该是 ip:7458/weChatGPT

**Comment by shenjia** [comment]
我了个汗

**Comment by shenjia** [comment]
我用caddyV2进行反向代理，怎么也转发不过去。caddyFile配置如下：
`
    handle_path /weChatGPT {
        reverse_proxy 127.0.0.1:7458
    }
`

访问实际域名下的/weChatGPT时，仍然提示`404 page not found.`
此时后台的日志是
`INFO[2022-12-13 20:05:43] "GET http://?????.de/ HTTP/1.1" from 127.0.0.1:56676 - 404 19B in 51.26µs`

如果用下面的caddeFile转发，前端访问则502

'    handle_path /weChatGPT {
        reverse_proxy 127.0.0.1:7458/weChatGPT
    }
'

这到底怎么转发才能把route透传过去啊……求助！

**Comment by shenjia** [comment]
搞定了，用下面的规则进行反向代理即可：

   handle_path /weChatGPT {
        rewrite * /weChatGPT
        reverse_proxy 127.0.0.1:7458
    }

**Comment by gtoxlili** [comment]
> 确实在 Readme里没写清楚 和微信公众平台对接的路由应该是 ip:7458/weChatGPT

[已修复](https://github.com/gtoxlili/wechat-chatGPT/commit/5b6b9cc66f5425287190d8a7c6098a603ee358c3)
