### ISSUE TITLE
怎样提高到15秒回复呢？

### ISSUE THREAD

**Issue by jasonxxp** [gtoxlili/wechat-chatGPT#8]
怎样提高到15秒回复呢？

**Comment by gtoxlili** [comment]
核心思路是从第一个请求来的时候开始执行耗时任务，等他执行完成后再返回给当前的请求(比如第二次或第三次的请求)具体实现见代码哦

**Comment by shenjia** [comment]
然而并没有什么卵用……15秒什么问题都回答不了
