### ISSUE TITLE
请求超时，导致服务自动退出

### ISSUE THREAD

**Issue by shenjia** [gtoxlili/wechat-chatGPT#9]
目前已经能正常开启对话，但仅能建立握手信息，提出问题就会超时。

INFO[2022-12-13 23:09:16] 用户 ogY6UuP9-yMo-VAyj4zlyBvYrOLY 启动新的对话
INFO[2022-12-13 23:09:21] [消息接收] Type: text, From: ogY6UuP9-yMo-VAyj4zlyBvYrOLY, MsgId: 23922168065204906, Content: 你好
INFO[2022-12-13 23:09:26] [消息接收] Type: text, From: ogY6UuP9-yMo-VAyj4zlyBvYrOLY, MsgId: 23922168065204906, Content: 你好
INFO[2022-12-13 23:09:28] "POST http://shenjia.de/weChatGPT?signature=c23ca0374ab7c05c78c7dc8be414eaacd7951638&timestamp=1670944156&nonce=364379646&openid=ogY6UuP9-yMo-VAyj4zlyBvYrOLY HTTP/1.1" from 127.0.0.1:42182 - 200 342B in 11.500110323s
INFO[2022-12-13 23:09:28] "POST http://shenjia.de/weChatGPT?signature=c23ca0374ab7c05c78c7dc8be414eaacd7951638&timestamp=1670944156&nonce=364379646&openid=ogY6UuP9-yMo-VAyj4zlyBvYrOLY HTTP/1.1" from 127.0.0.1:43854 - 200 342B in 1.417098614s
INFO[2022-12-13 23:09:28] "POST http://shenjia.de/weChatGPT?signature=c23ca0374ab7c05c78c7dc8be414eaacd7951638&timestamp=1670944156&nonce=364379646&openid=ogY6UuP9-yMo-VAyj4zlyBvYrOLY HTTP/1.1" from 127.0.0.1:43850 - 200 342B in 6.427933569s
INFO[2022-12-13 23:09:45] [消息接收] Type: text, From: ogY6UuP9-yMo-VAyj4zlyBvYrOLY, MsgId: 23922167016461479, Content: 为什么你的请求总超时？
INFO[2022-12-13 23:09:45] 用户 ogY6UuP9-yMo-VAyj4zlyBvYrOLY 继续对话
INFO[2022-12-13 23:09:50] [消息接收] Type: text, From: ogY6UuP9-yMo-VAyj4zlyBvYrOLY, MsgId: 23922167016461479, Content: 为什么你的请求总超时？
INFO[2022-12-13 23:09:55] [消息接收] Type: text, From: ogY6UuP9-yMo-VAyj4zlyBvYrOLY, MsgId: 23922167016461479, Content: 为什么你的请求总超时？
panic: context canceled

goroutine 27 [running]:
wxChatGPT/chatGPT/handler.(*UserInfo).SendMsg(0xc0003db700, {0x8051d8, 0xc000059980}, {0xc000259200, 0x45f}, 0xc000079b30, {0xc00045b6e0?, 0x0?})
	/root/wechat-chatGPT/chatGPT/handler/userHandler.go:58 +0x678
wxChatGPT/chatGPT.(*ChatGPT).SendMsg(0xc000012468, {0xc00045b6e0, 0x21}, {0xc0001748c0, 0x1c}, {0x8051d8, 0xc000059980})
	/root/wechat-chatGPT/chatGPT/chatGPT.go:119 +0x22f
wxChatGPT/chatGPT.(*ChatGPT).SendMsgChan.func1()
	/root/wechat-chatGPT/chatGPT/chatGPT.go:102 +0x3e
created by wxChatGPT/chatGPT.(*ChatGPT).SendMsgChan
	/root/wechat-chatGPT/chatGPT/chatGPT.go:101 +0x12e
exit status 2

**Comment by shenjia** [comment]
看了下微信开放平台的文档，貌似只有注册成服务号，才能使用客服消息功能来处理异步消息。哎，貌似无解了。

**Comment by gtoxlili** [comment]
自动退出的话应该是代码bug recover没有捕捉到吧我明天改一下

**Comment by shenjia** [comment]
> 理论上访问chatgpt流量少的时候还是可用的，可以试着在凌晨之类的时段使用，还有就是你获取cf-clearance的方案可以提个 merge request 嘛？

我提了啊

**Comment by gtoxlili** [comment]
[已修复](https://github.com/gtoxlili/wechat-chatGPT/commit/5b6b9cc66f5425287190d8a7c6098a603ee358c3)
